server:
  port: 10086
eureka:
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaService,默认是ture
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
    fetch-registry: true #是否拉取其他服务信息，默认是true

spring:
  application:
    name: mt_eureka